packages:
  - "apps/*"
  - "packages/*"

overrides:
  sharp: "0.35.3"
  postcss: "8.5.22"

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
