import { Badge } from "@perfume-aura/ui/components/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@perfume-aura/ui/components/card";
import { InquiryStatusForm } from "@/components/commerce/inquiry-status-form";
import { DbUnavailableState } from "@/components/db-empty-state";
import { listCommerceSupport } from "@/lib/commerce";
import { safeDbQuery } from "@/lib/db-safe";
import { requireCapability } from "@/lib/session";

export const dynamic = "force-dynamic";
export default async function CommerceSupportPage() {
  await requireCapability("commerce.support.manage", { redirectToLogin: true });
  const result = await safeDbQuery(() => listCommerceSupport());
  return <div className="mx-auto flex w-full max-w-6xl flex-col gap-6"><div><h1 className="font-heading text-2xl font-semibold tracking-tight">Customer support & returns</h1><p className="mt-1 text-sm text-muted-foreground">Contact, wholesale, return, and RTO work stay linked to accountable owner workflows.</p></div>{result.error || !result.data ? <DbUnavailableState message={result.error ?? "No data returned."} /> : <div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><Card><CardHeader><CardTitle>Inquiries</CardTitle><CardDescription>{result.data.inquiries.length} recent. Status changes are written to the operations audit trail.</CardDescription></CardHeader><CardContent className="grid gap-3">{result.data.inquiries.length === 0 ? <p className="text-sm text-muted-foreground">No inquiries have been received. New contact and wholesale messages will appear here after the public gate opens.</p> : result.data.inquiries.map((item) => <article key={item.id} className="grid gap-3 rounded-md border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><strong className="text-sm">{item.name}</strong><p className="mt-1 text-xs text-muted-foreground">{item.email}{item.businessName ? ` · ${item.businessName}` : ""}</p></div><div className="flex flex-wrap gap-2"><Badge variant="secondary">{item.kind} · {item.status.replace("_", " ")}</Badge><Badge variant="outline">notification {item.notificationStatus ?? "not queued"}{item.notificationAttemptCount ? ` · ${item.notificationAttemptCount}` : ""}</Badge></div></div><details className="text-sm"><summary className="cursor-pointer font-medium underline-offset-4 hover:underline">Read message</summary><p className="mt-2 whitespace-pre-wrap leading-6">{item.message}</p></details><p className="text-xs text-muted-foreground">Received {item.createdAt.toLocaleString("en-IN")} · consent {item.consentVersion}</p><InquiryStatusForm inquiryId={item.id} status={item.status} updatedAt={item.updatedAt.toISOString()} /></article>)}</CardContent></Card><Card><CardHeader><CardTitle>Returns</CardTitle><CardDescription>{result.data.returns.length} recent</CardDescription></CardHeader><CardContent className="grid gap-3">{result.data.returns.length === 0 ? <p className="text-sm text-muted-foreground">No return requests are waiting for review.</p> : result.data.returns.map((item) => <div key={item.id} className="rounded-md border p-3"><div className="flex justify-between gap-2"><strong className="text-sm">Order {item.orderId.slice(0, 8)}</strong><Badge variant="secondary">{item.status}</Badge></div><p className="mt-2 text-sm">{item.reason}</p></div>)}</CardContent></Card></div>}</div>;
}
